security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        our_db_provider:
          entity:
              class: App\Entity\User
              property: username

    firewalls:
        mains:
            pattern: ^/
            provider: our_db_provider
            anonymous: ~
            form_login:
                login_path: Connexion
                check_path: Connexion
            logout:
                path: Deconnexion
                target: Connexion
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path: /
                # by default, the feature is enabled by checking a
                # checkbox in the login form (see below), uncomment the
                # following line to always enable it.
                #always_remember_me: true


    encoders:
        App\Entity\User:
            algorithm: bcrypt
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/user, roles: ROLE_USER }
