<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\RegisterType;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class UserController extends AbstractController
{
    /**
     * @Route("/Inscription", name="user_register")
     */
    public function register(EntityManagerInterface $em, Request $request, UserPasswordEncoderInterface $encoder)
    {
        $user = new User();
        $user->setCreatedAt(new \DateTime());
        $user->setActive(true);

        $registerForm=$this->createForm(RegisterType::class, $user);
        $registerForm->handleRequest($request);
        if($registerForm->isSubmitted() && $registerForm->isValid()){
            //Hash password
            $hashed = $encoder->encodePassword($user, $user->getPassword());
            $user->setPassword($hashed);

            $photo = $registerForm->get('photo')->getData();
            if($photo){
                $photoName = $this->generateUniqueFileName().'.'.strtolower($photo->getClientOriginalExtension());
                $photo->move(
                    $this->getParameter('upload_photos'),
                    $photoName
                );
                $user->setPhoto($photoName);
            }



            $em->persist($user);
            $em->flush();

            return $this->redirectToRoute('main_home');
        }
        return $this->render("user/register.html.twig", [
            "registerForm" => $registerForm->createView(),
        ]);
    }

    /**
     * @Route("/Connexion", name="Connexion")
     */
    public function login(Request $request, AuthenticationUtils $au){

            $error = $au->getLastAuthenticationError();
            return $this->render('user/login.html.twig', [
                "error" => $error,
            ]);
    }

    /**
     * @Route("/Profil/{id}", name="user_profile", requirements={"id": "\d+"})
     */
    public function userProfile($id, EntityManagerInterface $em, UserRepository $ur, Request $request, UserPasswordEncoderInterface $encoder){
        $user = $ur->find($id);
        $profileForm = $this->createForm(RegisterType::class, $user);
        $photoIn = $user->getPhoto();

        $profileForm->handleRequest($request);
        if($profileForm->isSubmitted() && $profileForm->isValid()){
            //Hash password
            $hashed = $encoder->encodePassword($user, $user->getPassword());
            $user->setPassword($hashed);

            $photo = $profileForm->get('photo')->getData();
            if($photo){
                $photoName = $this->generateUniqueFileName().'.'.strtolower($photo->getClientOriginalExtension());
                $photo->move(
                    $this->getParameter('upload_photos'),
                    $photoName
                );
                $user->setPhoto($photoName);
            }else{
                $user->setPhoto($photoIn);
            }
            $em->flush();
        }
        return $this->render('user/profile.html.twig', [
            "profileForm" => $profileForm->createView(),
        ]);
    }

    /**
     * @Route("/Deconnexion", name="Deconnexion")
     */
    public function logout(){}

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}
